version: '3.7'

networks:
  back:
    external:
      name: infrastructure_back
services:
    mongo:
      image: mongo:3.6
      volumes:
        - /mnt/mongodb:/data/db
      networks:
        - back
      ports:
        - "27017:27017"
    images:
      build: ./image_service
      depends_on:
        - mongo
        - png
        - gif
      networks:
        - back
      ports:
        - "3000:3000"
    png:
      build: ./conversion_service
      environment:
        - CONVERT_FORMAT=png
      networks:
        - back
      ports:
        - "3001:3001"
      command: bundle exec rails s -p 3001 -b 0.0.0.0
    gif:
      build: ./conversion_service
      environment:
        - CONVERT_FORMAT=gif
      networks:
        - back
      ports:
        - "3002:3002"
      command: bundle exec rails s -p 3002 -b 0.0.0.0
    

